# Generated by Django 3.2.9 on 2022-08-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='groupnamemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='groupcreatemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=250)),
                ('galias', models.CharField(max_length=250)),
                ('gbehaves', models.CharField(max_length=250)),
                ('gallocate', models.CharField(max_length=250)),
                ('gunder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.groupnamemodel')),
            ],
        ),
    ]
