# Generated by Django 3.2.9 on 2022-08-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_ledgercreatemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgercreatemodel',
            name='lmname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ledgercreatemodel',
            name='lunder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.groupcreatemodel'),
        ),
    ]
