# Generated by Django 3.2.9 on 2022-08-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_groupanalysismodel_ledgeranalysismodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='groupanalysismodel',
        ),
        migrations.DeleteModel(
            name='ledgeranalysismodel',
        ),
    ]
