# Generated by Django 3.2.9 on 2022-08-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_groupvouchermodel_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='groupvouchermodel',
        ),
    ]
