# Generated by Django 3.2.9 on 2022-08-25 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_ledgervouchermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgervouchermodel',
            name='lstockitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ledgeranalysismodel'),
        ),
        migrations.AlterField(
            model_name='ledgervouchermodel',
            name='ludergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ledgercreatemodel'),
        ),
    ]
