# Generated by Django 3.2.9 on 2022-08-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20220824_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupvouchermodel',
            name='perticular',
        ),
    ]
