# Generated by Django 3.2.9 on 2022-08-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_groupvouchermodel_perticular'),
    ]

    operations = [
        migrations.DeleteModel(
            name='groupvouchermodel',
        ),
    ]
